### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#114]
```
Thread 1 "sfwbar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e4fc01 in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff7e4fc01 in g_type_check_instance_is_fundamentally_a ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7e3087d in g_object_unref ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x0000555555581f44 in scale_image_clear (self=0x55555589f5e0)
    at ../src/scaleimage.c:245
#3  0x0000555555582021 in scale_image_destroy (self=0x55555589f5e0)
    at ../src/scaleimage.c:254
#4  0x00007ffff7e2b4a5 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7e3f0f5 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7e40501 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7e46186 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7e46243 in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff79545ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff7e3239e in g_object_run_dispose ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff77b8310 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff771a9ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff7e2b4a5 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7e3f0f5 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff7e40501 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7e46186 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7e46243 in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff79545ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff7e3239e in g_object_run_dispose ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff771a9ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff7e2b4a5 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff7e3f0f5 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7e40501 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff7e46186 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff7e46243 in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff79545ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff7e3239e in g_object_run_dispose ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff771a9ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x000055555556d9cb in base_widget_destroy (self=0x55555589c980)
    at ../src/basewidget.c:77
#30 0x0000555555578171 in flow_item_destroy (self=0x55555589c980)
    at ../src/flowitem.c:22
#31 0x00007ffff7e2b540 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7e3f0f5 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7e40501 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff7e46186 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff7e46243 in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff79545ac in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff7e309c0 in g_object_unref ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff7718c5d in gtk_container_remove ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x000055555557697c in flow_grid_remove_widget
    (widget=0x55555589c980, parent=0x555555874760) at ../src/flowgrid.c:221
#40 0x00007ffff77b8310 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x0000555555576e51 in flow_grid_update (self=0x555555874760)
    at ../src/flowgrid.c:298
#42 0x000055555558ea76 in tray_update () at ../src/tray.c:106
#43 0x0000555555568511 in shell_timer (data=0x0) at ../src/sfwbar.c:126
#44 0x00007ffff71e2fee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007ffff71df099 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff71e22d7 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff71e28f0 in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff73b3b5d in g_application_run ()
    at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#49 0x0000555555568b3a in main (argc=1, argv=0x7fffffffe328)
    at ../src/sfwbar.c:241

```

**Comment by keshto** [comment]
My hunch is the bar is being mirrored on my 2 outputs is causing the issue.

**Comment by LBCrion** [comment]
I assume this is with the latest git version? Is it easily reproducible?

**Comment by LBCrion** [comment]
I think I found the reason. Would you mind testing to see if the latest git
behaves better?

**Comment by keshto** [comment]
no :( it fails much more quicker though.

```
Thread 1 "sfwbar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e4fc01 in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff7e4fc01 in g_type_check_instance_is_fundamentally_a ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7e3087d in g_object_unref ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x0000555555581f0a in scale_image_clear (self=0x5555559d7ff0)
    at ../src/scaleimage.c:245
#3  0x0000555555582320 in scale_image_set_pixbuf
    (self=0x5555559d7ff0, pb=0x55555599e480) at ../src/scaleimage.c:307
#4  0x000055555558eeb2 in tray_item_update (self=0x5555559fa510)
    at ../src/trayitem.c:53
#5  0x0000555555578749 in flow_item_update (self=0x5555559fa510)
    at ../src/flowitem.c:105
#6  0x0000555555576ea6 in flow_grid_update (self=0x555555878490)
    at ../src/flowgrid.c:308
#7  0x000055555558eaa8 in tray_update () at ../src/tray.c:109
#8  0x0000555555568511 in shell_timer (data=0x0) at ../src/sfwbar.c:126
#9  0x00007ffff71e2fee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff71df099 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff71e22d7 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff71e28f0 in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff73b3b5d in g_application_run ()
    at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#14 0x0000555555568b3a in main (argc=1, argv=0x7fffffffe328)
    at ../src/sfwbar.c:241
```

**Comment by LBCrion** [comment]
Ok,  this should be fixed now.  Can you try the latest git again please to
check that there is nothing else left?

**Comment by keshto** [comment]
So far looking good.

**Comment by keshto** [comment]
Been 24hrs no issue yet. Thanks!
