### ISSUE TITLE
sfwbar crashes after turning off monitor

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#243]
Single monitor setup. I assume 41021b0a0b501b1bc0f252fb540930f64de3f562 is the cause, because it worked fine before updating today.

```
❯  ./build/sfwbar
AddressSanitizer:DEADLYSIGNAL
=================================================================
==10828==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000a82a (pc 0x7f63db6951ad bp 0x000000000000 sp 0x7ffee37a21f0 T0)
==10828==The signal is caused by a READ memory access.
    #0 0x7f63db6951ad in wl_proxy_marshal_flags (/usr/lib64/libwayland-client.so.0+0x61ad)
    #1 0x7f63db98956a in zxdg_output_v1_destroy xdg-output-unstable-v1.h:403
    #2 0x7f63db989cdf in xdg_output_destroy ../src/gui/monitor.c:201
    #3 0x7f63db98a267 in monitor_removed_cb ../src/gui/monitor.c:275
    #4 0x7f63dc399e49 in g_cclosure_marshal_VOID__OBJECTv (/usr/lib64/libgobject-2.0.so.0+0x16e49)
    #5 0x7f63dc3963db  (/usr/lib64/libgobject-2.0.so.0+0x133db)
    #6 0x7f63dc3b003c  (/usr/lib64/libgobject-2.0.so.0+0x2d03c)
    #7 0x7f63dc3b9555 in g_signal_emit_valist (/usr/lib64/libgobject-2.0.so.0+0x36555)
    #8 0x7f63dc3b961a in g_signal_emit (/usr/lib64/libgobject-2.0.so.0+0x3661a)
    #9 0x7f63dc41ee09  (/usr/lib64/libgdk-3.so.0+0x2fe09)
    #10 0x7f63dc459f23  (/usr/lib64/libgdk-3.so.0+0x6af23)
    #11 0x7f63dc451707  (/usr/lib64/libgdk-3.so.0+0x62707)
    #12 0x7f63d9b6c30d  (/usr/lib64/libffi.so.8+0x830d)
    #13 0x7f63d9b6b157  (/usr/lib64/libffi.so.8+0x7157)
    #14 0x7f63d9b6bcda in ffi_call (/usr/lib64/libffi.so.8+0x7cda)
    #15 0x7f63db697c75  (/usr/lib64/libwayland-client.so.0+0x8c75)
    #16 0x7f63db6931be  (/usr/lib64/libwayland-client.so.0+0x41be)
    #17 0x7f63db69449a in wl_display_dispatch_queue_pending (/usr/lib64/libwayland-client.so.0+0x549a)
    #18 0x7f63dc454767  (/usr/lib64/libgdk-3.so.0+0x65767)
    #19 0x7f63dc41be63 in gdk_display_get_event (/usr/lib64/libgdk-3.so.0+0x2ce63)
    #20 0x7f63dc454475  (/usr/lib64/libgdk-3.so.0+0x65475)
    #21 0x7f63db6fe251  (/usr/lib64/libglib-2.0.so.0+0x5e251)
    #22 0x7f63db7017a7  (/usr/lib64/libglib-2.0.so.0+0x617a7)
    #23 0x7f63db70200f in g_main_context_iteration (/usr/lib64/libglib-2.0.so.0+0x6200f)
    #24 0x7f63daaede9c in g_application_run (/usr/lib64/libgio-2.0.so.0+0xede9c)
    #25 0x55c33b0d49ea in main ../src/sfwbar.c:194
    #26 0x7f63dac3038f  (/usr/lib64/libc.so.6+0x2638f)
    #27 0x7f63dac30448 in __libc_start_main (/usr/lib64/libc.so.6+0x26448)
    #28 0x55c33b0d3b44 in _start (/home/florian/Git/sfwbar/build/sfwbar+0x4b44)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libwayland-client.so.0+0x61ad) in wl_proxy_marshal_flags
==10828==ABORTING
```

**Comment by LBCrion** [comment]
Thank you for flagging this. This is what I get for playing with old code
without fully reading through it. Can you please check if the latest git is
behaving ok?
